#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgoThanhTien_2001200542_WebKFC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebGaRanKFC")]
	public partial class dbWebGaRanKFCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_HoaDon(tbl_HoaDon instance);
    partial void Updatetbl_HoaDon(tbl_HoaDon instance);
    partial void Deletetbl_HoaDon(tbl_HoaDon instance);
    partial void Inserttbl_ChiTietHoaDon(tbl_ChiTietHoaDon instance);
    partial void Updatetbl_ChiTietHoaDon(tbl_ChiTietHoaDon instance);
    partial void Deletetbl_ChiTietHoaDon(tbl_ChiTietHoaDon instance);
    partial void Inserttbl_Loai(tbl_Loai instance);
    partial void Updatetbl_Loai(tbl_Loai instance);
    partial void Deletetbl_Loai(tbl_Loai instance);
    partial void Inserttbl_KhachHang(tbl_KhachHang instance);
    partial void Updatetbl_KhachHang(tbl_KhachHang instance);
    partial void Deletetbl_KhachHang(tbl_KhachHang instance);
    partial void Inserttbl_MonAn(tbl_MonAn instance);
    partial void Updatetbl_MonAn(tbl_MonAn instance);
    partial void Deletetbl_MonAn(tbl_MonAn instance);
    partial void Inserttbl_NhanVien(tbl_NhanVien instance);
    partial void Updatetbl_NhanVien(tbl_NhanVien instance);
    partial void Deletetbl_NhanVien(tbl_NhanVien instance);
    #endregion
		
		public dbWebGaRanKFCDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebGaRanKFCConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbWebGaRanKFCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWebGaRanKFCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWebGaRanKFCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWebGaRanKFCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_HoaDon> tbl_HoaDons
		{
			get
			{
				return this.GetTable<tbl_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ChiTietHoaDon> tbl_ChiTietHoaDons
		{
			get
			{
				return this.GetTable<tbl_ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Loai> tbl_Loais
		{
			get
			{
				return this.GetTable<tbl_Loai>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KhachHang> tbl_KhachHangs
		{
			get
			{
				return this.GetTable<tbl_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MonAn> tbl_MonAns
		{
			get
			{
				return this.GetTable<tbl_MonAn>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhanVien> tbl_NhanViens
		{
			get
			{
				return this.GetTable<tbl_NhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HoaDon")]
	public partial class tbl_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHoaDon;
		
		private System.Nullable<int> _maKH;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<int> _maNV;
		
		private EntityRef<tbl_ChiTietHoaDon> _tbl_ChiTietHoaDon;
		
		private EntityRef<tbl_KhachHang> _tbl_KhachHang;
		
		private EntityRef<tbl_NhanVien> _tbl_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHoaDonChanging(int value);
    partial void OnmaHoaDonChanged();
    partial void OnmaKHChanging(System.Nullable<int> value);
    partial void OnmaKHChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnmaNVChanging(System.Nullable<int> value);
    partial void OnmaNVChanged();
    #endregion
		
		public tbl_HoaDon()
		{
			this._tbl_ChiTietHoaDon = default(EntityRef<tbl_ChiTietHoaDon>);
			this._tbl_KhachHang = default(EntityRef<tbl_KhachHang>);
			this._tbl_NhanVien = default(EntityRef<tbl_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="Int")]
		public System.Nullable<int> maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._tbl_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int")]
		public System.Nullable<int> maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._tbl_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HoaDon_tbl_ChiTietHoaDon", Storage="_tbl_ChiTietHoaDon", ThisKey="maHoaDon", OtherKey="maHoaDon", IsUnique=true, IsForeignKey=false)]
		public tbl_ChiTietHoaDon tbl_ChiTietHoaDon
		{
			get
			{
				return this._tbl_ChiTietHoaDon.Entity;
			}
			set
			{
				tbl_ChiTietHoaDon previousValue = this._tbl_ChiTietHoaDon.Entity;
				if (((previousValue != value) 
							|| (this._tbl_ChiTietHoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_ChiTietHoaDon.Entity = null;
						previousValue.tbl_HoaDon = null;
					}
					this._tbl_ChiTietHoaDon.Entity = value;
					if ((value != null))
					{
						value.tbl_HoaDon = this;
					}
					this.SendPropertyChanged("tbl_ChiTietHoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhachHang_tbl_HoaDon", Storage="_tbl_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public tbl_KhachHang tbl_KhachHang
		{
			get
			{
				return this._tbl_KhachHang.Entity;
			}
			set
			{
				tbl_KhachHang previousValue = this._tbl_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tbl_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_KhachHang.Entity = null;
						previousValue.tbl_HoaDons.Remove(this);
					}
					this._tbl_KhachHang.Entity = value;
					if ((value != null))
					{
						value.tbl_HoaDons.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVien_tbl_HoaDon", Storage="_tbl_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public tbl_NhanVien tbl_NhanVien
		{
			get
			{
				return this._tbl_NhanVien.Entity;
			}
			set
			{
				tbl_NhanVien previousValue = this._tbl_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhanVien.Entity = null;
						previousValue.tbl_HoaDons.Remove(this);
					}
					this._tbl_NhanVien.Entity = value;
					if ((value != null))
					{
						value.tbl_HoaDons.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ChiTietHoaDon")]
	public partial class tbl_ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHoaDon;
		
		private int _maMonAn;
		
		private System.Nullable<int> _maKH;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<int> _SoLuong;
		
		private string _DonViTinh;
		
		private EntityRef<tbl_HoaDon> _tbl_HoaDon;
		
		private EntityRef<tbl_MonAn> _tbl_MonAn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHoaDonChanging(int value);
    partial void OnmaHoaDonChanged();
    partial void OnmaMonAnChanging(int value);
    partial void OnmaMonAnChanged();
    partial void OnmaKHChanging(System.Nullable<int> value);
    partial void OnmaKHChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    #endregion
		
		public tbl_ChiTietHoaDon()
		{
			this._tbl_HoaDon = default(EntityRef<tbl_HoaDon>);
			this._tbl_MonAn = default(EntityRef<tbl_MonAn>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					if (this._tbl_HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonAn", DbType="Int NOT NULL")]
		public int maMonAn
		{
			get
			{
				return this._maMonAn;
			}
			set
			{
				if ((this._maMonAn != value))
				{
					if (this._tbl_MonAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonAnChanging(value);
					this.SendPropertyChanging();
					this._maMonAn = value;
					this.SendPropertyChanged("maMonAn");
					this.OnmaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="Int")]
		public System.Nullable<int> maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HoaDon_tbl_ChiTietHoaDon", Storage="_tbl_HoaDon", ThisKey="maHoaDon", OtherKey="maHoaDon", IsForeignKey=true)]
		public tbl_HoaDon tbl_HoaDon
		{
			get
			{
				return this._tbl_HoaDon.Entity;
			}
			set
			{
				tbl_HoaDon previousValue = this._tbl_HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._tbl_HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_HoaDon.Entity = null;
						previousValue.tbl_ChiTietHoaDon = null;
					}
					this._tbl_HoaDon.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietHoaDon = this;
						this._maHoaDon = value.maHoaDon;
					}
					else
					{
						this._maHoaDon = default(int);
					}
					this.SendPropertyChanged("tbl_HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MonAn_tbl_ChiTietHoaDon", Storage="_tbl_MonAn", ThisKey="maMonAn", OtherKey="id", IsForeignKey=true)]
		public tbl_MonAn tbl_MonAn
		{
			get
			{
				return this._tbl_MonAn.Entity;
			}
			set
			{
				tbl_MonAn previousValue = this._tbl_MonAn.Entity;
				if (((previousValue != value) 
							|| (this._tbl_MonAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_MonAn.Entity = null;
						previousValue.tbl_ChiTietHoaDons.Remove(this);
					}
					this._tbl_MonAn.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietHoaDons.Add(this);
						this._maMonAn = value.id;
					}
					else
					{
						this._maMonAn = default(int);
					}
					this.SendPropertyChanged("tbl_MonAn");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Loai")]
	public partial class tbl_Loai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLoai;
		
		private string _TenLoai;
		
		private EntitySet<tbl_MonAn> _tbl_MonAns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(int value);
    partial void OnmaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public tbl_Loai()
		{
			this._tbl_MonAns = new EntitySet<tbl_MonAn>(new Action<tbl_MonAn>(this.attach_tbl_MonAns), new Action<tbl_MonAn>(this.detach_tbl_MonAns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(100)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Loai_tbl_MonAn", Storage="_tbl_MonAns", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<tbl_MonAn> tbl_MonAns
		{
			get
			{
				return this._tbl_MonAns;
			}
			set
			{
				this._tbl_MonAns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_MonAns(tbl_MonAn entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Loai = this;
		}
		
		private void detach_tbl_MonAns(tbl_MonAn entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Loai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhachHang")]
	public partial class tbl_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKH;
		
		private string _HoTen;
		
		private string _NgaySinh;
		
		private string _SDT;
		
		private string _Email;
		
		private string _UserName;
		
		private string _Password;
		
		private EntitySet<tbl_HoaDon> _tbl_HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(int value);
    partial void OnmaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public tbl_KhachHang()
		{
			this._tbl_HoaDons = new EntitySet<tbl_HoaDon>(new Action<tbl_HoaDon>(this.attach_tbl_HoaDons), new Action<tbl_HoaDon>(this.detach_tbl_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(150)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NVarChar(50)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(150)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhachHang_tbl_HoaDon", Storage="_tbl_HoaDons", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<tbl_HoaDon> tbl_HoaDons
		{
			get
			{
				return this._tbl_HoaDons;
			}
			set
			{
				this._tbl_HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_HoaDons(tbl_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhachHang = this;
		}
		
		private void detach_tbl_HoaDons(tbl_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MonAn")]
	public partial class tbl_MonAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<double> _Price;
		
		private string _Images;
		
		private string _DonViTinh;
		
		private System.Nullable<int> _maLoai;
		
		private EntitySet<tbl_ChiTietHoaDon> _tbl_ChiTietHoaDons;
		
		private EntityRef<tbl_Loai> _tbl_Loai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPriceChanging(System.Nullable<double> value);
    partial void OnPriceChanged();
    partial void OnImagesChanging(string value);
    partial void OnImagesChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnmaLoaiChanging(System.Nullable<int> value);
    partial void OnmaLoaiChanged();
    #endregion
		
		public tbl_MonAn()
		{
			this._tbl_ChiTietHoaDons = new EntitySet<tbl_ChiTietHoaDon>(new Action<tbl_ChiTietHoaDon>(this.attach_tbl_ChiTietHoaDons), new Action<tbl_ChiTietHoaDon>(this.detach_tbl_ChiTietHoaDons));
			this._tbl_Loai = default(EntityRef<tbl_Loai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images", DbType="NChar(150)")]
		public string Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				if ((this._Images != value))
				{
					this.OnImagesChanging(value);
					this.SendPropertyChanging();
					this._Images = value;
					this.SendPropertyChanged("Images");
					this.OnImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="Int")]
		public System.Nullable<int> maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._tbl_Loai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MonAn_tbl_ChiTietHoaDon", Storage="_tbl_ChiTietHoaDons", ThisKey="id", OtherKey="maMonAn")]
		public EntitySet<tbl_ChiTietHoaDon> tbl_ChiTietHoaDons
		{
			get
			{
				return this._tbl_ChiTietHoaDons;
			}
			set
			{
				this._tbl_ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Loai_tbl_MonAn", Storage="_tbl_Loai", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public tbl_Loai tbl_Loai
		{
			get
			{
				return this._tbl_Loai.Entity;
			}
			set
			{
				tbl_Loai previousValue = this._tbl_Loai.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Loai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Loai.Entity = null;
						previousValue.tbl_MonAns.Remove(this);
					}
					this._tbl_Loai.Entity = value;
					if ((value != null))
					{
						value.tbl_MonAns.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Loai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_ChiTietHoaDons(tbl_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_MonAn = this;
		}
		
		private void detach_tbl_ChiTietHoaDons(tbl_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_MonAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhanVien")]
	public partial class tbl_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNV;
		
		private string _tenNV;
		
		private string _UserName;
		
		private string _Password;
		
		private EntitySet<tbl_HoaDon> _tbl_HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(int value);
    partial void OnmaNVChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public tbl_NhanVien()
		{
			this._tbl_HoaDons = new EntitySet<tbl_HoaDon>(new Action<tbl_HoaDon>(this.attach_tbl_HoaDons), new Action<tbl_HoaDon>(this.detach_tbl_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(150)")]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(150)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVien_tbl_HoaDon", Storage="_tbl_HoaDons", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<tbl_HoaDon> tbl_HoaDons
		{
			get
			{
				return this._tbl_HoaDons;
			}
			set
			{
				this._tbl_HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_HoaDons(tbl_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVien = this;
		}
		
		private void detach_tbl_HoaDons(tbl_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVien = null;
		}
	}
}
#pragma warning restore 1591
