<?xml version="1.0" encoding="utf-8"?><Database Name="WebGaRanKFC" Class="dbWebGaRanKFCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-FRMKN0GD\TIEN;Initial Catalog=WebGaRanKFC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebGaRanKFCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_HoaDon" Member="tbl_HoaDons">
    <Type Name="tbl_HoaDon">
      <Column Name="maHoaDon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="maNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_HoaDon_tbl_ChiTietHoaDon" Member="tbl_ChiTietHoaDon" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="tbl_ChiTietHoaDon" Cardinality="One" />
      <Association Name="tbl_KhachHang_tbl_HoaDon" Member="tbl_KhachHang" ThisKey="maKH" OtherKey="maKH" Type="tbl_KhachHang" IsForeignKey="true" />
      <Association Name="tbl_NhanVien_tbl_HoaDon" Member="tbl_NhanVien" ThisKey="maNV" OtherKey="maNV" Type="tbl_NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ChiTietHoaDon" Member="tbl_ChiTietHoaDons">
    <Type Name="tbl_ChiTietHoaDon">
      <Column Name="maHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maMonAn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Association Name="tbl_HoaDon_tbl_ChiTietHoaDon" Member="tbl_HoaDon" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="tbl_HoaDon" IsForeignKey="true" />
      <Association Name="tbl_MonAn_tbl_ChiTietHoaDon" Member="tbl_MonAn" ThisKey="maMonAn" OtherKey="id" Type="tbl_MonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Loai" Member="tbl_Loais">
    <Type Name="tbl_Loai">
      <Column Name="maLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tbl_Loai_tbl_MonAn" Member="tbl_MonAns" ThisKey="maLoai" OtherKey="maLoai" Type="tbl_MonAn" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_KhachHang" Member="tbl_KhachHangs">
    <Type Name="tbl_KhachHang">
      <Column Name="maKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="tbl_KhachHang_tbl_HoaDon" Member="tbl_HoaDons" ThisKey="maKH" OtherKey="maKH" Type="tbl_HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MonAn" Member="tbl_MonAns">
    <Type Name="tbl_MonAn">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="maLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_MonAn_tbl_ChiTietHoaDon" Member="tbl_ChiTietHoaDons" ThisKey="id" OtherKey="maMonAn" Type="tbl_ChiTietHoaDon" />
      <Association Name="tbl_Loai_tbl_MonAn" Member="tbl_Loai" ThisKey="maLoai" OtherKey="maLoai" Type="tbl_Loai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_NhanVien" Member="tbl_NhanViens">
    <Type Name="tbl_NhanVien">
      <Column Name="maNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="tbl_NhanVien_tbl_HoaDon" Member="tbl_HoaDons" ThisKey="maNV" OtherKey="maNV" Type="tbl_HoaDon" />
    </Type>
  </Table>
</Database>